version: '3'
services:
  db:
    image: mariadb:10
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mypetsafe
      MARIADB_USERNAME: admin
      MARIADB_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./volumes:/var/lib/mysql
    networks:
      - mypetsafe
      
networks:
  mypetsafe:
    driver: bridge
